/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: components["parameters"]["cursor"];
                    /** @description Number of items per page (default 50, max 200) */
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Next-Cursor"?: string;
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        /**
         * Create a submission
         * @description Upload a file (pdf, docx, jpg, png — max 10MB) **or** provide `editorText` (UTF-8). Returns a minimal ack with parsing/ocr status.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        assignmentId: string;
                        studentId: string;
                        /** @description Optional, used in storage path grouping */
                        grade?: string | null;
                        /**
                         * Format: binary
                         * @description One of `file` **or** `editorText` must be provided
                         */
                        file?: string;
                        /** @description Alternative to `file`; plain text */
                        editorText?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionCreated"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Payload too large (max 10MB) */
                413: {
                    headers: {
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unsupported media type */
                415: {
                    headers: {
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a submission */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Submission"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a locator for the original artifact
         * @description Returns either a 302 redirect to a time-limited URL (Azure) or the file itself (local dev).
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File content (local dev) */
                200: {
                    headers: {
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Redirect to download URL */
                302: {
                    headers: {
                        /** @description Temporary download URL */
                        Location?: string;
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List courses */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: components["parameters"]["cursor"];
                    /** @description Number of items per page (default 50, max 200) */
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Cursor for next page (empty or omitted if end) */
                        "X-Next-Cursor"?: string;
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: components["parameters"]["cursor"];
                    /** @description Number of items per page (default 50, max 200) */
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Filter by role */
                    role?: components["schemas"]["UserRole"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Next-Cursor"?: string;
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assignments */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: components["parameters"]["cursor"];
                    /** @description Number of items per page (default 50, max 200) */
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Restrict to a specific course */
                    courseId?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Next-Cursor"?: string;
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignmentList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grades */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: components["parameters"]["cursor"];
                    /** @description Number of items per page (default 50, max 200) */
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Restrict to a specific assignment */
                    assignmentId?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Next-Cursor"?: string;
                        "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GradeList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            correlationId?: string | null;
            details?: {
                [key: string]: unknown;
            };
        };
        MetaLms: {
            /**
             * @description LMS source (e.g., google-classroom, vklass, unikum)
             * @example google-classroom
             */
            provider?: string;
            /** @description Arbitrary LMS-specific fields (lossless surface) */
            fields?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        UserRole: "student" | "teacher" | "admin";
        /** @example {
         *       "id": "gc_user_42",
         *       "role": "teacher",
         *       "givenName": "Ada",
         *       "familyName": "Lovelace",
         *       "email": "ada@example.edu",
         *       "source": "google-classroom",
         *       "externalId": "42"
         *     } */
        User: {
            id: string;
            role: components["schemas"]["UserRole"];
            givenName?: string | null;
            familyName?: string | null;
            /** Format: email */
            email?: string | null;
            /** @example google-classroom */
            source: string;
            externalId?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            meta?: {
                lms?: components["schemas"]["MetaLms"];
            };
        };
        UserList: {
            items?: components["schemas"]["User"][];
            count?: number;
        };
        /** @example {
         *       "id": "gc_123",
         *       "title": "Matematik 7A",
         *       "teacherIds": [
         *         "gc_user_42"
         *       ],
         *       "source": "google-classroom",
         *       "externalId": "123",
         *       "meta": {
         *         "lms": {
         *           "provider": "google-classroom",
         *           "fields": {
         *             "room": "A12"
         *           }
         *         }
         *       }
         *     } */
        Course: {
            id: string;
            title: string;
            code?: string | null;
            period?: string | null;
            teacherIds?: string[];
            /** @example google-classroom */
            source: string;
            externalId?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            meta?: {
                lms?: components["schemas"]["MetaLms"];
            };
        };
        CourseList: {
            items?: components["schemas"]["Course"][];
            count?: number;
        };
        /** @enum {string} */
        AssignmentStatus: "draft" | "published" | "closed";
        /** @example {
         *       "id": "gc_asg_9",
         *       "courseId": "gc_123",
         *       "title": "Veckans uppgift",
         *       "dueAt": "2025-10-05T12:00:00Z",
         *       "status": "published",
         *       "source": "google-classroom",
         *       "externalId": "9"
         *     } */
        Assignment: {
            id: string;
            courseId: string;
            title: string;
            description?: string | null;
            /** Format: date-time */
            dueAt?: string | null;
            status?: components["schemas"]["AssignmentStatus"];
            /** @example google-classroom */
            source: string;
            externalId?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            meta?: {
                lms?: components["schemas"]["MetaLms"];
            };
        };
        AssignmentList: {
            items?: components["schemas"]["Assignment"][];
            count?: number;
        };
        /** @enum {string} */
        GradeStatus: "graded" | "pending";
        /** @example {
         *       "id": "gc_grade_55",
         *       "assignmentId": "gc_asg_9",
         *       "studentId": "gc_user_7",
         *       "score": 18,
         *       "scale": "points",
         *       "status": "graded",
         *       "source": "google-classroom",
         *       "externalId": "55"
         *     } */
        Grade: {
            id: string;
            assignmentId: string;
            studentId: string;
            score?: number | null;
            /** @example points|percentage|A-F */
            scale?: string | null;
            status?: components["schemas"]["GradeStatus"];
            /** @example google-classroom */
            source: string;
            externalId?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            meta?: {
                lms?: components["schemas"]["MetaLms"];
            };
        };
        GradeList: {
            items?: components["schemas"]["Grade"][];
            count?: number;
        };
        /** @enum {string} */
        SubmissionStatus: "received" | "error" | "deleted";
        /** @enum {string} */
        ExtractionStatus: "parsed" | "pending_ocr";
        /** @example {
         *       "id": "sub_2f6e...",
         *       "assignmentId": "gc_asg_9",
         *       "studentId": "gc_user_7",
         *       "classId": "7A",
         *       "mime": "application/pdf",
         *       "size": 524288,
         *       "status": "received",
         *       "extractionStatus": "pending_ocr",
         *       "ocrRequired": true,
         *       "extractedText": null,
         *       "storagePath": "class/7A/gc_asg_9/sub_2f6e.../original.pdf",
         *       "createdAt": "2025-09-29T08:00:00Z",
         *       "updatedAt": "2025-09-29T08:00:00Z"
         *     } */
        Submission: {
            id: string;
            assignmentId: string;
            studentId: string;
            classId?: string | null;
            mime: string;
            size: number;
            status: components["schemas"]["SubmissionStatus"];
            extractionStatus: components["schemas"]["ExtractionStatus"];
            ocrRequired: boolean;
            extractedText?: string | null;
            /** @description Blob path */
            storagePath?: string;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            meta?: {
                lms?: components["schemas"]["MetaLms"];
            };
        };
        /** @example {
         *       "submissionId": "sub_2f6e...",
         *       "status": "received",
         *       "extractionStatus": "pending_ocr",
         *       "ocrRequired": true
         *     } */
        SubmissionCreated: {
            submissionId: string;
            status: components["schemas"]["SubmissionStatus"];
            extractionStatus: components["schemas"]["ExtractionStatus"];
            ocrRequired: boolean;
        };
        SubmissionList: {
            items?: components["schemas"]["Submission"][];
            count?: number;
        };
    };
    responses: {
        /** @description Forbidden (invalid API key) */
        Forbidden: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing API key */
        Unauthorized: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Cursor for pagination */
        cursor: string | null;
        /** @description Number of items per page (default 50, max 200) */
        pageSize: number;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation ID (set/echoed by gateway/backend) */
        "X-Correlation-Id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
